name: Deploy Laravel Project to cPanel
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Hanya ambil commit terakhir, tidak perlu history .git

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Sesuaikan dengan versi PHP Anda
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Sesuaikan dengan versi Node Anda

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build  # atau npm run prod untuk Laravel Mix

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: ðŸ“‚ Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/  # Ganti dengan path yang benar di cPanel Anda
          exclude: |
            **/.git*
            **/.git*/**
            .git/**
            node_modules/**
            tests/**
            .env.example
            .editorconfig
            .gitignore
            .gitattributes
            phpunit.xml
            README.md
